# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt


2024-04-18 17:13:01.496682: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
tf.__version__

'2.16.1'

# Data Preprocessing 

## Importing Dataset

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
dataset.drop(labels = ["RowNumber", "CustomerId", "Surname"], axis = 1, inplace = True)

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

## Encoding Categorical Data

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [9]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

## Splitting dataset into train and test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

## Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building ANN

## Initializing ANN

In [14]:
ann = tf.keras.models.Sequential()

## Building the input layer and adding the first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

## Adding second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

## Adding output layer

In [17]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

# Training the ANN

## Compiling ANN

In [18]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics =['accuracy'])

## Training ANN on Train set

In [19]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7725 - loss: 0.6417
Epoch 2/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7993 - loss: 0.5345
Epoch 3/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 779us/step - accuracy: 0.7957 - loss: 0.4993
Epoch 4/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - accuracy: 0.7891 - loss: 0.4802
Epoch 5/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - accuracy: 0.7930 - loss: 0.4502
Epoch 6/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.8006 - loss: 0.4301
Epoch 7/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.8129 - loss: 0.4227
Epoch 8/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step - accuracy: 0.8106 - loss: 0.4242
Epoch 9/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8231 - loss: 0.4003
Epoch 10/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 736us/step - accuracy: 0.8233 - loss: 0.4098
Epoch 11/100
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 690us/step - accuracy: 0.8229 - loss: 0.4018
Epoch 12/100
210/210 

# Making Predictions and Evaluating the model

## Predicting results of single observation

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[[0.02388552]]


In [21]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[False]]


### There is a probability of 0.023 that the above person will leave the bank, Hence we can predict that this person will stay with the bank.

## Predicting the test results

In [29]:
y_pred = ann.predict(X_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

104/104 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


## Confusion matrix and accuracy 

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2542  115]
 [ 313  330]]


0.8703030303030304